version: "3.1"
services:
    alan_db:
        image: mysql
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: dbname
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        volumes:
            - persistent:/var/lib/mysql
        networks:
            - default
    macias_www:
        build: .
        ports: 
            - "80:80"
        volumes:
            - ./www:/var/www/html
        links:
            - alan_db
        networks:
            - default
    mamani_phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - alan_db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
    
    alan_web_python:
        build: ./www/registro_productos
        ports:
            - "5000:5000"
        networks:
            - default
    macias_mongodb:
        image: "mongo"
        restart: always
        ports:
            - "27017:27017"
        networks:
            - default
volumes:
    persistent:
